

SET(MPI_SRC_POSSIBLE_LIBRARY_PATH
  $ENV{MPI_SRC}
  )

FIND_LIBRARY(OMPI_LIBRARY
  NAMES mpi
  PATHS 
  ${MPI_SRC_POSSIBLE_LIBRARY_PATH}/ompi/.libs
  NO_DEFAULT_PATH
  )

FIND_LIBRARY(ORTE_LIBRARY
  NAMES open-rte
  PATHS 
  ${MPI_SRC_POSSIBLE_LIBRARY_PATH}/orte/.libs
  NO_DEFAULT_PATH
  )

FIND_LIBRARY(OPAL_LIBRARY
  NAMES open-pal
  PATHS 
  ${MPI_SRC_POSSIBLE_LIBRARY_PATH}/opal/.libs
  NO_DEFAULT_PATH
  )

IF(OMPI_LIBRARY)
  LIST(APPEND MPI_SRC_LIBRARIES "${OMPI_LIBRARY}")
ELSE(OMPI_LIBRARY)
  MESSAGE("mpi library not found.")
ENDIF(OMPI_LIBRARY)

IF(ORTE_LIBRARY)
  LIST(APPEND MPI_SRC_LIBRARIES "${ORTE_LIBRARY}")
ELSE(ORTE_LIBRARY)
  MESSAGE("open-rte library not found.")
ENDIF(ORTE_LIBRARY)

IF(OPAL_LIBRARY)
  LIST(APPEND MPI_SRC_LIBRARIES "${OPAL_LIBRARY}")
ELSE(OPAL_LIBRARY)
  MESSAGE("open-pal library not found.")
ENDIF(OPAL_LIBRARY)

# --------------------------------

MARK_AS_ADVANCED(
  MPI_SRC_LIBRARIES
)

include( FindPackageHandleStandardArgs ) 
find_package_handle_standard_args( MPI_SRC 
    REQUIRED_VARS 
        MPI_SRC_LIBRARIES 
) 
